### PR TITLE
Multiple universes in one time

### PR DESCRIPTION
**Pull request by dehimer**

### CODE REVIEW

**Comment by hhromic** [comment]
Thanks for this pull request and the nice idea to improve multiple universe handling!
I already implemented your changes on my local copy (with a small fix I had to do to your code) and I'm updating the README file. I will release a new version of the library hopefully tomorrow. Stay tuned to update your local copy.

Thanks again!
Hugo.

**Comment by hhromic** [comment]
I implemented your proposed changes along more improvements to the lib. Thanks!

**Comment by dehimer** [comment]
You are welcome!) Thank you

**Comment by hhromic** [comment]
Hope it is more useful for you now, beware that one breaking change is that I renamed the getter/setter functions for packet channel data to packet slots data.
Let me know if you find any other bugs!

**Comment by dehimer** [comment]
Good chance to test) I still busy with project where I use your library
Will pull it asap

**Pull request closed without merging**
